---
title: "Pressure Relief Toy for DIL"
author: "YukunYang"
date: "April 16, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)

```

```{r cars}
hs=read_csv("hastages with info.csv")
edges=hs[,c(2,3,5)]
nodes=unique(hs[,5])

```
```{r}
over_ten <-  edges %>% group_by(.dots=c("from","to")) %>% summarise(n=n()) %>% filter(n>25)
over_ten_nodes <- dplyr::as_data_frame(unique(append(unique(over_ten$to),unique(over_ten$from))))
colnames(over_ten_nodes) <- "id"
colnames(over_ten) <- c("from","to","value")
over_ten_nodes$label=over_ten_nodes$id
library(visNetwork)
library(igraph)
graph <- graph.data.frame(over_ten, directed = F)
degree_value <- degree(graph)

c_spin <- spinglass.community(graph)
mod=data.frame(names=c_spin$names, group=c_spin$membership)


over_ten_nodes$value <- degree_value[match(over_ten_nodes$id, names(degree_value))]
over_ten_nodes <- merge(over_ten_nodes,mod,by.x = "id", by.y ="names")
over_ten_nodes$color.background <- c("orange", "pink", "yellow", "blue","gold","purple","lightblue","black","darkblue","darkred","green","lightgreen","lightblue","darkgreen","darkyellow")[over_ten_nodes$group]

visNetwork(over_ten_nodes,over_ten)%>% 
  visOptions(highlightNearest = TRUE) %>% visOptions(selectedBy = "group")%>% 
  visHierarchicalLayout()
```





```{r}
print(c_spin[])
```
































```{r}

```

This is the end